services:
  pygeoapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: pygeoapi-growbike:local
    container_name: pygeoapi-growbike
    ports:
      - "9000:80"
    volumes:
      - ./pygeoapi-config.yml:/pygeoapi/local.config.yml:ro
    environment:
      PYGEOAPI_CONFIG: /pygeoapi/local.config.yml
      PYGEOAPI_SERVER_URL: http://localhost:5000
    restart: unless-stopped
