# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2025 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limits:
        default_items: 20
        max_items: 50
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: TinyDB
        connection: /tmp/pygeoapi-process-manager.db
        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net
    admin: false # enable admin api

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    growbike:
        type: process
        processor:
            name: growbike
        inputs:
          cityname:
            title: City Name
            description: Name of city to run analysis on
            schema:
              type: string

          proj_crs:
            title: Proj crs
            description: CRS to be used for projection
            schema:
              type: string

          ranking:
            title: Ranking
            description: measure to be used for ranking edges
            schema:
              type: string
              default: betweenness_centrality

          seed_point_type:
            title: Seed point type
            description: what seed points to use for generation of network
            schema:
              type: string
              default: grid

          seed_point_grid_spacing:
            title: Seed point grid spacing
            description: if grid is used this is the spacing between seed points, in meters
            schema:
              type: integer
              default: 1707

          seed_point_delta:
            title: Seed point delta
            description: Maximum distance between seed points and osm nodes
            schema:
              type: integer
              default: 500

          existing_network_spacing:
            title: Existing network spacing
            description: spacing between seed points with existing network. If not set to positive integer existing network is ignored
            schema:
              type: integer
              default: None

          export_data:
            title: Export data
            description: always set to False since data would be stored on host machine
            schema:
              type: boolean
              default: False

        outputs:
          result:
            title: Growbike result
            schema:
              type: object
              format: geojson-feature-collection
